<?php
/**
* Jomres CMS Agnostic Plugin
* @author Woollyinwales IT <sales@jomres.net>
* @version Jomres 9 
* @package Jomres
* @copyright	2005-2015 Woollyinwales IT
* Jomres (tm) PHP files are released under both MIT and GPL2 licenses. This means that you can choose the license that best suits your project.
**/

// ################################################################
defined( '_JOMRES_INITCHECK' ) or die( 'Direct Access to this file is not allowed.' );
// ################################################################

class j06000save_magic_menu
	{
	function __construct()
		{
		$MiniComponents =jomres_getSingleton('mcHandler');
		if ($MiniComponents->template_touch)
			{
			$this->template_touchable=false; return;
			}
		
		if (!JOMRES_MAGIC_MENU_CONTINUE)
			return;
		
		$ePointFilepath = get_showtime('ePointFilepath');
		
		$thisJRUser=jomres_getSingleton('jr_user');
		
		$menu_name		 = trim(jomresGetParam( $_REQUEST, 'menu_name', '' ));
		$search_url		 = trim(jomresGetParam( $_REQUEST, 'search_url', '' ));
		
		if ( $thisJRUser->superPropertyManager && $menu_name != "" && $search_url != "")
			{
			$pageoutput = array();
			$output = array();
			
			$section_name	 = trim(jomresGetParam( $_REQUEST, 'section_name', '' ));
			
			if ($section_name != "")
				{
				$section_translation_string ='jr_gettext( \'_JOMRES_MAGIC_MENUS_CUSTOMSEARCH_'.strtoupper($section_name).'\' , "'.$section_name.'" ,false,false)';
				$section_touchtemplate_string = '$output[]		=jr_gettext(\'_JOMRES_MAGIC_MENUS_CUSTOMSEARCH_'.strtoupper($section_name).'\', "'.$section_name.'");';
				}
			else
				{
				$section_translation_string ='jr_gettext( "_JOMRES_MAGIC_MENUS_CUSTOMSEARCHES" , _JOMRES_MAGIC_MENUS_CUSTOMSEARCHES ,false,false)';
				$section_touchtemplate_string = '$output[]		=jr_gettext(\'_JOMRES_MAGIC_MENUS_CUSTOMSEARCHES\', \'_JOMRES_MAGIC_MENUS_CUSTOMSEARCHES\');';
				}
			
			$new_scriptname = preg_replace("/[^a-zA-Z0-9\s]/", "", $menu_name);
			$new_scriptname = str_replace('  ','',$new_scriptname);
			$new_scriptname = str_replace(' ','_',$new_scriptname); // Must be underscore here, can't use hyphens as they'll cause php errors
			
			$pattern = $this->get_script_pattern();
			$url = str_replace('&#38;','&',$search_url);
			$pattern = str_replace ("XX_SEARCH_URL_XX",$url ,$pattern);
			$pattern = str_replace ("XX_SCRIPTNAME_XX",$new_scriptname ,$pattern);
			$pattern = str_replace ("XX_MENUTITLE_XX", $menu_name, $pattern);
			
			$new_filename = "j00009".$new_scriptname.".class.php";

			$fp=fopen(JOMRES_MAGIC_MENU_PLUGIN_DIR.$new_filename,'w');
			fwrite($fp, $pattern );
			fclose($fp);

			$registry = jomres_singleton_abstract::getInstance( 'minicomponent_registry' );
			$registry->regenerate_registry();
	
			jomresRedirect( jomresURL( $url ) ); 
			}
		}
	
	function get_script_pattern()
		{
		$pattern = '<?php
// Automagically generated by magic menu plugin
defined( \'_JOMRES_INITCHECK\' ) or die( \'\' );

class j00009XX_SCRIPTNAME_XX
	{
	function j00009XX_SCRIPTNAME_XX()
		{
		$MiniComponents =jomres_getSingleton(\'mcHandler\');
		if ($MiniComponents->template_touch)
			{
			$this->template_touchable=false; return;
			}
			
			$jomres_menu = jomres_singleton_abstract::getInstance(\'jomres_menu\');
			$jomres_menu->add_item(70, jr_gettext(\'_JOMRES_CUSTOMCODE_MAGICMENU_XX_SCRIPTNAME_XX\',\'XX_MENUTITLE_XX\',false), \'XX_SEARCH_URL_XX\', \'fa-list\', true);
		}

	function getRetVals()
		{
		return $this->cpanelButton;
		}
	}
';
		return $pattern;
		}

	// This must be included in every Event/Mini-component
	function getRetVals()
		{
		return null;
		}
	}
